package com.example.backend.controller;

import com.example.backend.dto.ApiResponse;
import com.example.backend.dto.ShortenerResponse;
import com.example.backend.security.UserPrincipal;
import com.example.backend.service.ShortenerService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * API for listing the current user's short links (QR codes).
 * Each short link can be represented as a QR code on the frontend.
 */
@RestController
@RequestMapping("/api/qr-codes")
@RequiredArgsConstructor
public class QrCodeController {

    private final ShortenerService shortenerService;

    /**
     * List all QR codes (short links) generated by the current user.
     */
    @GetMapping
    public ResponseEntity<ApiResponse<List<ShortenerResponse>>> listMyQrCodes(
            @AuthenticationPrincipal UserPrincipal principal) {
        List<ShortenerResponse> list = shortenerService.findAllByUserId(principal.getId());
        return ResponseEntity.ok(ApiResponse.success("OK", list));
    }
}
